apiVersion: v1
kind: Service
metadata:
  name: devhub-webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devhub-webapp
  labels:
    account: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      serviceAccountName: devhub-webapp
      containers:
        - name: webapp
          image: steven8519/webapp
          imagePullPolicy: IfNotPresent
