apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    service: webapp
spec:
  ports:
    - port: 30080
      name: http
  type: NodePort
  selector:
    app: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devhub-webapp
  labels:
    account: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      serviceAccountName: devhub-webapp
      containers:
        - name: webapp
          image: steven8519/webapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30080
